apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rancher-ai-agent
  name: rancher-ai-agent
  namespace: cattle-ai-agent-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-ai-agent
  template:
    metadata:
      labels:
        app: rancher-ai-agent
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not .Values.insecureSkipTls }}
      serviceAccountName: ca-reader-sa
      {{- end }}
      {{- if or (not .Values.insecureSkipTls) .Values.rag.pvc }}
      volumes:
      {{- if not .Values.insecureSkipTls }}
      - name: mcp-ca-volume
        secret:
          secretName: cattle-mcp-ca
      {{- end }}
      {{- if .Values.rag.pvc }}
      - name: rag-storage
        persistentVolumeClaim:
          claimName: "{{ .Values.rag.pvc }}"
      {{- end }}
      {{- end }}
      containers:
      - image: "{{ .Values.aiAgent.image.repository }}:{{ .Values.aiAgent.image.tag }}"
        imagePullPolicy: "{{ .Values.aiAgent.image.pullPolicy }}"
        name: agent
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: OPENAI_API_KEY
                optional: true
          - name: OPENAI_URL
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: OPENAI_URL
                optional: true
          - name: MODEL
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: MODEL
                optional: true
          - name: OLLAMA_URL
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: OLLAMA_URL
                optional: true
          - name: GOOGLE_API_KEY
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: GOOGLE_API_KEY
                optional: true
          - name: ACTIVE_LLM
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: ACTIVE_LLM
                optional: true
          - name: SYSTEM_PROMPT
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: SYSTEM_PROMPT
                optional: true
          - name: ENABLE_RAG
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: ENABLE_RAG
                optional: true
          - name: EMBEDDINGS_MODEL
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: EMBEDDINGS_MODEL
                optional: true
          - name: LANGFUSE_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: LANGFUSE_PUBLIC_KEY
                optional: true
          - name: LANGFUSE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: LANGFUSE_SECRET_KEY
                optional: true
          - name: LANGFUSE_HOST
            valueFrom:
              secretKeyRef:
                name: llm-config
                key: LANGFUSE_HOST
                optional: true
          - name: LOG_LEVEL
            value: "{{ .Values.log.level }}"
          - name: INSECURE_SKIP_TLS
            value: "{{ .Values.insecureSkipTls }}"
        ports:
         - containerPort: 8000
        {{- if or (not .Values.insecureSkipTls) .Values.rag.pvc }}
        volumeMounts:
        {{- if not .Values.insecureSkipTls }}
          - name: mcp-ca-volume
            mountPath: /etc/tls
            readOnly: true
        {{- end }}
        {{- if .Values.rag.pvc }}
          - name: rag-storage
            mountPath: /app/rag
        {{- end }}
        {{- end }}
