{{- if .Values.dbManager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-ai-db
  labels:
    app: rancher-ai-db
spec:
  replicas: {{ .Values.db.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rancher-ai-db
  template:
    metadata:
      labels:
        app: rancher-ai-db
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.db.postgres.image.repository }}:{{ .Values.db.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.db.postgres.image.pullPolicy }}
          env:
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.db.postgres.password }}"
            - name: POSTGRES_USER
              value: "{{ .Values.db.postgres.user }}"
            - name: POSTGRES_DB
              value: "{{ .Values.db.postgres.name }}"
            - name: PGPORT
              value: "5432"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -h localhost -p 5432 -U ${POSTGRES_USER}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -h localhost -p 5432 -U ${POSTGRES_USER}
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: rancher-ai-postgres-pvc
{{- end }}