apiVersion: v1
kind: Secret
metadata:
  name: llm-config
  namespace: cattle-ai-agent-system
type: Opaque
stringData:
  OPENAI_API_KEY: "{{ .Values.openaiApiKey }}"
  OPENAI_URL: "{{ .Values.openaiUrl }}"
  SYSTEM_PROMPT: {{ .Values.systemPrompt | quote }}
  MODEL: "{{ .Values.llmModel }}"
  OLLAMA_URL: "{{ .Values.ollamaUrl }}"
  GOOGLE_API_KEY: "{{ .Values.googleApiKey }}"
  ACTIVE_LLM: "{{ .Values.activeLlm }}"
  ENABLE_RAG: "{{ .Values.rag.enabled }}"
  EMBEDDINGS_MODEL: "{{ .Values.rag.embeddings_model }}"
  LANGFUSE_HOST: "{{ .Values.langfuseHost }}"
  LANGFUSE_PUBLIC_KEY: "{{ .Values.langfusePublicKey }}"
  LANGFUSE_SECRET_KEY: "{{ .Values.langfuseSecretKey }}"
  AWS_REGION: "{{ .Values.awsBedrock.region }}"
  AWS_BEARER_TOKEN_BEDROCK: "{{ .Values.awsBedrock.bearerToken }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.awsBedrock.secretAccessKey }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.awsBedrock.accessKeyId }}"
