apiVersion: v1
kind: Service
metadata:
  name: rancher-mcp-server
  namespace: cattle-ai-agent-system
spec:
  selector:
    app: rancher-mcp-server
  ports:
    - port: 80
      name: http
      targetPort: 9092
      protocol: TCP
    - port: 443
      name: https
      targetPort: 9092
      protocol: TCP
  type: ClusterIP