[project]
name = "e2e"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest>=9.0.1",
    "testcontainers>=4.13.3",
    "testcontainers-core>=0.0.1rc1",
]
