aiAgent:
  image:
    repository: ghcr.io/rancher-sandbox/rancher-ai-agent
    tag: v0.1.1-alpha.15
    pullPolicy: IfNotPresent
mcp:
  image:
    repository: ghcr.io/rancher-sandbox/rancher-ai-mcp
    tag: v0.0.1-alpha.25
    pullPolicy: IfNotPresent

llmModel: ""
ollamaLlmModel: ""
geminiLlmModel: ""
openaiLlmModel: ""
bedrockLlmModel: ""
ollamaUrl: ""
googleApiKey:
openaiApiKey:
openaiUrl:
awsBedrock:
  bearerToken:
  accessKeyId:
  secretAccessKey:
  region:
activeLlm: # ollama, gemini, openai, bedrock
# Enable RAG with embedded rancher documentation
rag:
    enabled: false
    embeddings_model:
    pvc:
langfuseSecretKey:
langfusePublicKey:
langfuseHost:
insecureSkipTls: false
log:
  level: info
